[package]
name = "wasm-game-of-life"
version = "0.1.0"
authors = ["bt7878 <brandontosteis@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
console_error_panic_hook =  "0.1.6"


[profile.release]
opt-level = "s"
